apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-eu-only-app
  labels:
    app: catalog-eu-only-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: catalog-eu-only-app
  template:
    metadata:
      labels:
        app: catalog-eu-only-app
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
